#!/bin/bash

LAYOUT=${1:-"horizontal"}
COLOR=${2:-"37"}

CPUS=$(nproc --all)
LOAD_ALL=$(cat /proc/loadavg)
LOAD_1M_PERCENT=$(echo "${LOAD_ALL}" | awk "{print (\$1/${CPUS})*100}" | awk '{printf "%0.1f",$i}')
LOAD_5M_PERCENT=$(echo "${LOAD_ALL}" | awk "{print (\$2/${CPUS})*100}" | awk '{printf "%0.1f",$i}')
LOAD_15M_PERCENT=$(echo "${LOAD_ALL}" | awk "{print (\$3/${CPUS})*100}" | awk '{printf "%0.1f",$i}')
LOAD_SUMMARY="${LOAD_1M_PERCENT}% ${LOAD_5M_PERCENT}% ${LOAD_15M_PERCENT}% of ${CPUS} CPUs"

MEMORY_PERCENT=$(free | grep Mem | awk '{print ($3/$2)*100}' | awk '{printf "%0.1f",$i}')
MEMORY_TOTAL=$(free -h --si | grep Mem | awk '{print $2}')
MEMORY_SUMMARY="${MEMORY_PERCENT}% of ${MEMORY_TOTAL}"

SWAP_TOTAL=$(free -h --si | grep Swap | awk '{print $2}')
if [[ "${SWAP_TOTAL}" == "0B" ]]
then
  SWAP_PERCENT="0"
  SWAP_SUMMARY="-"
else
  SWAP_PERCENT=$(free | grep Swap | awk '{print ($3/$2)*100}' | awk '{printf "%0.1f",$i}')
  SWAP_SUMMARY="${SWAP_PERCENT}% of ${SWAP_TOTAL}"
fi

DISK_PERCENT=$( df -H | grep '/$' | awk '{print $5}')
DISK_TOTAL=$( df -H | grep '/$' | awk '{print $2}')
DISK_SUMMARY="${DISK_PERCENT} of ${DISK_TOTAL}"

echo -en "\e[${COLOR}m"

if [[ "${LAYOUT}" == "vertical" ]]
then
  TABLE=""
  TABLE+="Root disk, ${DISK_SUMMARY}\n"
  TABLE+="Memory, ${MEMORY_SUMMARY}\n"
  TABLE+="Swap, ${SWAP_SUMMARY}\n"
  TABLE+="Load, ${LOAD_SUMMARY}\n"
else
  HEADER="Root disk, Memory, Swap, 1m,5m,15m,Load"
  DATA="${DISK_SUMMARY}, ${MEMORY_SUMMARY}, ${SWAP_SUMMARY}, ${LOAD_1M_PERCENT}%,${LOAD_5M_PERCENT}%,${LOAD_15M_PERCENT}%,of ${CPUS} CPUs"
  TABLE="${HEADER}\n${DATA}"
fi
OUTPUT=$(echo -e "${TABLE}" | column --table --separator , --output-separator '  ') || TABLE="${ROWS}"
echo -e "${OUTPUT}"
echo -en "\e[0m"