#!/bin/bash
set -uo pipefail
GREEN="\e[32m"
RED="\e[31m"
GREY="\e[37m"
RESET="\e[0m"
Y="${GREEN} ✔ ${GREY}"
N="${RED} ✘ ${GREY}"
P="${GREY} ⏲ ${GREY}"

function move-cursor-up {
  declare -i N
  [[ -v "1" ]] && N="$1" || N="1"
  echo -ne '\e['"${N}"'A'
}

echo-table () {
  move-cursor-up 4
  HEADER1=", Ping, Ping, Curl, Curl, Network, IP, IP"
  HEADER2=", IP, DNS, IP, DNS, Interface, Internal, External"
  ROW1="IPv4, ${PING_IP_V4:-${P}}, ${PING_DNS_V4:-${P}}, ${CURL_IP_V4:-${P}}, ${CURL_DNS_V4:-${P}}, ${INTERFACE_V4:-${P}}, ${INTERNAL_V4:-${P}}, ${EXTERNAL_V4:-${P}}"
  ROW2="IPv6, ${PING_IP_V6:-${P}}, ${PING_DNS_V6:-${P}}, ${CURL_IP_V6:-${P}}, ${CURL_DNS_V6:-${P}}, ${INTERFACE_V6:-${P}}, ${INTERNAL_V6:-${P}}, ${EXTERNAL_V6:-${P}}"
  ROWS="${HEADER1}\n${HEADER2}\n${ROW1}\n${ROW2}"
  TABLE=$(echo -e "${ROWS}" | column --table --separator , --output-separator ' ') || TABLE="${ROWS}"
  echo -e "${TABLE}"
}

echo -ne "${GREY}"
echo -e "\n\n\n\n"
echo-table

INTERFACE_V4=$(ip route get 1.1.1.1 | awk -F "dev " 'NR==1{split($2,a," ");print a[1]}')
INTERFACE_V6=$(ip route get 2606:4700:4700::1111 | awk -F "dev " 'NR==1{split($2,a," ");print a[1]}')
INTERNAL_V4=$(ip route get 1.1.1.1 | awk -F "src " 'NR==1{split($2,a," ");print a[1]}')
INTERNAL_V6=$(ip route get 2606:4700:4700::1111 | awk -F "src " 'NR==1{split($2,a," ");print a[1]}')
echo-table

# PING_IP_V4
ping 1.1.1.1 -4 -c 1 -q -w 1 > /dev/null && PING_IP_V4="${Y}" || PING_IP_V4="${N}"
echo-table

# PING_IP_V6
ping 2606:4700:4700::1111 -6 -c 1 -q -w 1 > /dev/null && PING_IP_V6="${Y}" || PING_IP_V6="${N}"
echo-table

# PING_DNS_V4
ping one.one.one.one -4 -c 1 -q -w 1 > /dev/null && PING_DNS_V4="${Y}" || PING_DNS_V4="${N}"
echo-table

# PING_DNS_V6
ping one.one.one.one -6 -c 1 -q -w 1 > /dev/null && PING_DNS_V6="${Y}" || PING_DNS_V6="${N}"
echo-table

# CURL_IP_V4
curl 1.1.1.1 -4 --connect-timeout 1 --silent > /dev/null && CURL_IP_V4="${Y}" || CURL_IP_V4="${N}"
echo-table

# CURL_IP_V6
curl 'http://[2600:1901:0:7c33:0:0:0:0]:80/' -H 'Host: v6.ipinfo.io' -6 --connect-timeout 1 --silent && CURL_IP_V6="${Y}" || CURL_IP_V6="${N}"
echo-table

# CURL_DNS_V4
if EXTERNAL_V4=$(curl ipinfo.io/ip -4 --connect-timeout 1 --silent --fail)
then
  CURL_DNS_V4="${Y}"
else
  CURL_DNS_V4="${N}"
  EXTERNAL_V4="${N}"
fi
echo-table

# CURL_DNS_V6
if EXTERNAL_V6=$(curl v6.ipinfo.io/ip -6 --connect-timeout 1 --silent --fail)
then
  CURL_DNS_V6="${Y}"
else
  CURL_DNS_V6="${N}"
  EXTERNAL_V6="${N}"
fi
echo-table

echo -ne "${RESET}"
