#!/bin/bash
set -euo pipefail

REMOTE_HOST="${1}"

echo-success () {
  echo -e "\e[32m ✔  $1\e[0m" >&2
}

echo-information () {
  echo -e "\e[34m ⓘ  $1\e[0m" >&2
}

echo-error () {
  echo -e "\e[31m !  $1\e[0m" >&2
}

echo-warning () {
  echo -e "\e[33m ⚠  $1\e[0m" >&2
}

echo-subsidiary () {
  echo -e "\e[37m    $1\e[0m" >&2
}

echo-step () {
  echo -e "\e[0m »  $1\e[0m" >&2
}

if [[ ! -v 1 ]] 
then
  echo-error "Remote host is required"
  exit 1
fi

remote-backup-files "${REMOTE_HOST}" /data
remote-backup-sqlite "${REMOTE_HOST}" /data
remote-backup-files "${REMOTE_HOST}" /config
remote-backup-sqlite "${REMOTE_HOST}" /config
remote-archive "${REMOTE_HOST}"
