name: Run

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:

  run:
    name: Run
    runs-on: ${{ inputs.os }}
    steps:

      - name: Read Metadata
        run: |
          echo "OS: ${{ inputs.os }}"
          echo "Command: ${{ inputs.command }}"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run
        run: |
          for file in *
          do
            echo "${file}"
            sudo bash "${file}"
          done