name: Run

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      file:
        required: true
        type: string

jobs:

  run:
    name: ${{ inputs.file }} ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:

      - name: Read Metadata
        run: |
          echo "OS: ${{ inputs.os }}"
          echo "File: ${{ inputs.file }}"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run
        run: sudo bash ${{ inputs.file }}