name: Install

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:

  install:
    name: Install
    runs-on: ${{ inputs.os }}
    steps:

      - name: Read Metadata
        run: |
          echo "OS: ${{ inputs.os }}"
          echo "File: ${{ inputs.file }}"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install
        run: sudo bash ${{ inputs.file }}