name: Publish

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

      - name: Read Metadata
        run: |
          echo "Version: ${{ inputs.version }}"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Upload Release Assets
        working-directory: artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for file in ./*
          do
            echo "${file}"
            gh release upload "v${{ inputs.version }}" "${file}"
          done
          