name: CI/CD

on:
  push:

jobs:
    
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.analysis.outputs.files }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Analysis
        id: analysis              
        run: |
          FILES=$(ls | jq --raw-input | jq --slurp --compact-output 'map(select(. != "CNAME" and . != "LICENSE" and . != "README.md" and . != "src"))')
          echo "${FILES}"
          echo "files=${FILES}" >> $GITHUB_OUTPUT

  run:
    name: Run
    needs:
      - analysis
    uses: ./.github/workflows/01-run.yml
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJSON(needs.analysis.outputs.files) }}
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    with:
      file: ${{ matrix.file }}
      os: ${{ matrix.os }}
    secrets: inherit

  release:
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    name: Create Release
    needs:
      - run
    uses: StudioLE/Actions/.github/workflows/01-semantic-release.yml@main
    secrets: inherit
    
#  publish:
#    name: Publish
#    needs: 
#      - release
#      - run
#    if: ${{ needs.release.outputs.version != '0.0.0' }}
#    uses: ./.github/workflows/05-publish.yml
#    with:
#      version: ${{ needs.release.outputs.version }}
#    secrets: inherit