name: CI/CD

on:
  push:

jobs:

  run:
    name: Run
    uses: ./.github/workflows/01-run.yml
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
    with:
      os: ${{ matrix.os }}
    secrets: inherit

  release:
    name: Create Release
    needs:
      - run
    uses: StudioLE/Actions/.github/workflows/01-semantic-release.yml@main
    secrets: inherit
    
#  publish:
#    name: Publish
#    needs: 
#      - release
#      - run
#    if: ${{ needs.release.outputs.version != '0.0.0' }}
#    uses: ./.github/workflows/05-publish.yml
#    with:
#      version: ${{ needs.release.outputs.version }}
#    secrets: inherit