name: CI/CD

on:
  push:

jobs:

  release:
    name: Create Release
    uses: StudioLE/Actions/.github/workflows/01-semantic-release.yml@main
    secrets: inherit

  run:
    name: Run
    needs: release
    uses: ./.github/workflows/02-run.yml
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
        command:
          - broot
          - ncdu
    with:
      os: ${{ matrix.os }}
      command: ${{ matrix.command }}
    secrets: inherit
    
  publish:
    name: Publish
    needs: 
      - release
      - run
    if: ${{ needs.release.outputs.version != '0.0.0' }}
    uses: ./.github/workflows/05-publish.yml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit